# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
run_weighted_lowess <- function(x, y, w, span, npts, iterations) {
    .Call('_WeightedLowess_tests_run_weighted_lowess', PACKAGE = 'WeightedLowess.tests', x, y, w, span, npts, iterations)
}

