// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// run_weighted_lowess
Rcpp::List run_weighted_lowess(Rcpp::NumericVector x, Rcpp::NumericVector y, Rcpp::NumericVector w, double span, int npts, int iterations);
RcppExport SEXP _WeightedLowess_tests_run_weighted_lowess(SEXP xSEXP, SEXP ySEXP, SEXP wSEXP, SEXP spanSEXP, SEXP nptsSEXP, SEXP iterationsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type w(wSEXP);
    Rcpp::traits::input_parameter< double >::type span(spanSEXP);
    Rcpp::traits::input_parameter< int >::type npts(nptsSEXP);
    Rcpp::traits::input_parameter< int >::type iterations(iterationsSEXP);
    rcpp_result_gen = Rcpp::wrap(run_weighted_lowess(x, y, w, span, npts, iterations));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_WeightedLowess_tests_run_weighted_lowess", (DL_FUNC) &_WeightedLowess_tests_run_weighted_lowess, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_WeightedLowess_tests(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
