on:
  push:
    branches:
      - master

name: Doxygenate the API

jobs:
  doxygenator:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@v1.1.0
      with:
        working-directory: docs/
    - name: GH Pages Deployment
      uses: JamesIves/github-pages-deploy-action@4.1.3
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: docs/html
        target-folder: docs/
        clean: true # Automatically remove deleted files from the deploy branch
